version: '3.7'

services:
  rabbitmq:
    image: "masstransit/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
      - "5671:5671"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"